### ISSUE TITLE
Install & using troubles

### ISSUE THREAD

**Issue by Stan92** [recogizer/angular-gauge-chart#1]
Hi,
I m trying to use your component with ng5.
Using this line 
import { GaugeChartComponent } from 'angular-gauge-chart';
I got an error saying this module is not found.
I tried 
import { GaugeChartComponent } from '@recogizer/angular-gauge-chart' but I get a lot of warnings

```

WARNING in ./node_modules/@recogizer/angular-gauge-chart/node_modules/@angular/core/@angular/core.es5.js
5870:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Dev2018\testgauge\test201806.Web\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/@recogizer/angular-gauge-chart/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@recogizer/angular-gauge-chart/dist/bundle.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/@recogizer/angular-gauge-chart/node_modules/@angular/core/@angular/core.es5.js
5886:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compiler.js:506:17)
    at C:\Dev2018\testgauge\test201806.Web\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (C:\Dev2018\testgauge\test201806.Web\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ ./node_modules/@recogizer/angular-gauge-chart/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/@recogizer/angular-gauge-chart/dist/bundle.js
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

Did I miss something?
Regards,

**Comment by cherurg** [comment]
@Stan92 hi, Stan
Does the library work in your browser?

**Comment by Stan92** [comment]
Hi
What do u mean by if it works in my browser?
The online demo works fine for me but I suppose it was not your question :-)

**Comment by cherurg** [comment]
@Stan92 yep. After the installation, are you able to run it?
I don't use Windows, but I remember that 2-3 years ago I faced tons of warnings in `npm install` logs and usually it worked fine after the installation. 

Or maybe `npm install` finishes with an error code?

**Comment by Stan92** [comment]
The installation perfectly worked 
Any error from the npm install (any warning also) 
The problem comes from the import of the 
GaugeChartComponent that is not recognized

**Comment by cherurg** [comment]
@Stan92 
Next week I'll try to reproduce the problem. I'll post here when I get any result.

**Comment by Stan92** [comment]
I thank you in advance :-)

**Comment by pandiyaavps** [comment]
I have also problem on import of the
GaugeChartComponent

**Comment by cherurg** [comment]
@pandiyaavps thank you! I will try it and update the code.

**Comment by cherurg** [comment]
@pandiyaavps I applied your code, thank you!

I published the updated version, you can get it with `npm i angular-gauge-chart@0.5.0` (you can check out the [changelog](https://github.com/recogizer/angular-gauge-chart/blob/master/CHANGELOG.md)). 

I'm closing the issue for now, but if it appears again then let me know.
